apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fitpub.configMapName" . }}
  labels:
    {{- include "fitpub.labels" . | nindent 4 }}
  {{- with (include "fitpub.metaAnnotations" (dict "annotations" (dict) "context" $)) }}
  {{- . | nindent 2 }}
  {{- end }}
data:
  {{- range $key, $value := .Values.config }}
  {{- if not (kindIs "invalid" $value) }}
  {{- if ne ($value | toString) "" }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
