apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fitpub.fullname" . }}
  labels:
    {{- include "fitpub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fitpub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fitpub.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "fitpub.fullname" . }}-config
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: uploads
              mountPath: /app/uploads
            {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: uploads
          persistentVolumeClaim:
            claimName: {{ include "fitpub.fullname" . }}-uploads
        {{- end }}
