{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "fitpub.fullname" . }}
  labels:
    {{- include "fitpub.labels" . | nindent 4 }}
  {{- with (include "fitpub.metaAnnotations" (dict "annotations" (dict) "context" $)) }}
  {{- . | nindent 2 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "fitpub.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- $cpuTarget := .Values.autoscaling.targetCPUUtilizationPercentage | toString -}}
    {{- if ne $cpuTarget "" }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- $memTarget := .Values.autoscaling.targetMemoryUtilizationPercentage | toString -}}
    {{- if ne $memTarget "" }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
