{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "fitpub.fullname" . }}
  labels:
    {{- include "fitpub.labels" . | nindent 4 }}
  {{- $ann := include "fitpub.annotations" (dict "annotations" (dict) "context" $) }}
  {{- if $ann }}
  annotations:
    {{- $ann | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "fitpub.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  {{- if or .Values.networkPolicy.ingress.enabled .Values.networkPolicy.ingress.extraRules }}
  ingress:
    {{- if .Values.networkPolicy.ingress.enabled }}
    - ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
      {{- with .Values.networkPolicy.ingress.from }}
      from:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- with .Values.networkPolicy.ingress.extraRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if or .Values.networkPolicy.egress.allowAll .Values.networkPolicy.egress.extraRules }}
  egress:
    {{- if .Values.networkPolicy.egress.allowAll }}
    - {}
    {{- end }}
    {{- with .Values.networkPolicy.egress.extraRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
