{{- if not .Values.applicationSecret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fitpub.secretName" . }}
  labels:
    {{- include "fitpub.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.applicationSecret.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
