{{- if not .Values.applicationSecret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fitpub.secretName" . }}
  labels:
    {{- include "fitpub.labels" . | nindent 4 }}
  {{- $ann := include "fitpub.annotations" (dict "annotations" (dict) "context" $) }}
  {{- if $ann }}
  annotations:
    {{- $ann | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.applicationSecret.data }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
