apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fitpub.fullname" . }}-config
  labels:
    {{- include "fitpub.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
