{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fitpub.serviceAccountName" . }}
  labels:
    {{- include "fitpub.labels" . | nindent 4 }}
  {{- $ann := include "fitpub.annotations" (dict "annotations" .Values.serviceAccount.annotations "context" $) }}
  {{- if $ann }}
  annotations:
    {{- $ann | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
